---
title: "XGBoosted Model_NBA"
author: "Ramtin Talebi"
output: pdf_document
---

```{r}
require(caTools)
require(gam)
require(xgboost)
require(Matrix)
library(readr)
library(stringr)
library(car)
library(dplyr)

df <- read.csv("~/Desktop/NBA Analytics/Business Analytics/training_set_extended.csv")
#head(df)
df_descriptions <- df %>% 
  mutate(num_people = str_count(Description, "@"),
         num_hash = str_count(Description, "#"))
# Model: XGBoosted Linear Regression Model
# For videos, not using description data
df_prelim = df_descriptions[df$Type == 'Video',]
set.seed(123)
df_prelim <- df_prelim[sample(1:nrow(df_prelim)), ]
numeric_df <- subset(df_prelim, select=c(Followers, num_hash, num_people))
time_df <- model.matrix(~weekday+is_playoffs+day_time-1,df_prelim)
df_vid_net <- cbind(numeric_df, time_df)
df_vid_matrix <- data.matrix(df_vid_net)
df_vid_labels_prematrix <- subset(df_prelim, select=Engagements)
df_vid_labels <- data.matrix(df_vid_labels_prematrix)
#set.seed(123) 

# Sample Training and Testing Sets
numberOfTrainingSamples <- round(length(df_prelim$Engagements) * .75)
train_data <- df_vid_matrix[1:numberOfTrainingSamples,]
train_labels <- df_vid_labels[1:numberOfTrainingSamples,]
test_data <- df_vid_matrix[-(1:numberOfTrainingSamples),]
test_labels <- df_vid_labels[-(1:numberOfTrainingSamples),]

# DMatrix formation
dtrain <- xgb.DMatrix(data = train_data, label= train_labels)
dtest <- xgb.DMatrix(data = test_data, label= test_labels)

# Create XGBoosting Model
boost_model <- xgboost(data = dtrain, # the data   
                 nround = 75, max.depth = 2, early_stopping_rounds = 2)

#Calculate MAPE
actual = test_labels
predicted = predict(boost_model, dtest)
mape = mean(abs((actual - predicted)/actual) * 100)
mape

# Conclusion: This doesn't outperform much, but has the potential too. Potentially adding in data from descriptions and using 'ensemble methods' (which I have to review a bit) could make this be our top go.
```

```{r}

df_vid = df[df$Type == 'Video',]
set.seed(123) 
sample = sample.split(df_vid, SplitRatio = 0.75)
train_vid = subset(df_vid, sample == TRUE)
test_vid = subset(df_vid, sample == FALSE) 
fit = lm(Engagements ~ Followers + year + month + weekday + day_time + is_playoffs, data = train_vid)
summary(fit) # remove is_playoffs
fit.2 = lm(Engagements ~ Followers + year + month + weekday + day_time, data = train_vid)
summary(fit.2)

actual = test_vid$Engagements
predicted = predict(fit.2, test_vid)
mape = mean(abs((actual - predicted)/actual) * 100)
mape # = 9.72, decent number to baseline against

```