---
title: "NBA Hackathon Extra Stuff"
output: pdf_document
---

```{r}

#Prepare for training and validating XGBoosted Model
numeric_df <- subset(test_data_net, select=c(Followers, wkdy_num, num_hash, Followers_Mentioned, Type_num,all_nba,predicted))
time_df <- model.matrix(~is_playoffs+day_time-1,test_data_net)
df_XGnet <- cbind(numeric_df, time_df)
df_XGmatrix <- data.matrix(df_XGnet)
df_XGlabels_prematrix <- subset(test_data_net, select=Engagements)
df_XGlabels <- data.matrix(df_XGlabels_prematrix)

```

Next, we prepare our data into matrices for use with xgboost for our holdout data.

```{r}
## Split data set into training and test sets for first model
set.seed(125) 

# Sample Training and Testing Sets

numeric_df_Video <- subset(test_dataRF_Video, select=c(Followers, wkdy_num, num_hash, Followers_Mentioned, Type_num,all_nba,league_type,month_int,predicted))
numeric_df_Album <- subset(test_dataRF_Album, select=c(Followers, wkdy_num, num_hash, Followers_Mentioned, Type_num,all_nba,league_type,month_int,predicted))
numeric_df_Photo <- subset(test_dataRF_Photo, select=c(Followers, wkdy_num, num_hash, Followers_Mentioned, Type_num,all_nba,league_type,month_int,predicted))

time_df_Video <- model.matrix(~is_playoffs+day_time-1,test_dataRF_Video)
time_df_Album <- model.matrix(~is_playoffs+day_time-1,test_dataRF_Album)
time_df_Photo <- model.matrix(~is_playoffs+day_time-1,test_dataRF_Photo)

XG_Video_net <- cbind(numeric_df_Video, time_df_Video)
XG_Album_net <- cbind(numeric_df_Album, time_df_Album)
XG_Photo_net <- cbind(numeric_df_Photo, time_df_Photo)

XG_Video_matrix <- data.matrix(XG_Video_net)
XG_Album_matrix <- data.matrix(XG_Album_net)
XG_Photo_matrix <- data.matrix(XG_Photo_net)

XG_Video_labels_prematrix <- subset(test_dataRF_Video, select=Engagements)
XG_Album_labels_prematrix <- subset(test_dataRF_Album, select=Engagements)
XG_Photo_labels_prematrix <- subset(test_dataRF_Photo, select=Engagements)

XG_Video_labels <- data.matrix(XG_Video_labels_prematrix)
XG_Album_labels <- data.matrix(XG_Album_labels_prematrix)
XG_Photo_labels <- data.matrix(XG_Photo_labels_prematrix)

numberOfTrainingSamples_XGVideo <- round(length(test_dataRF_Video$Engagements) * .80)
numberOfTrainingSamples_XGAlbum <- round(length(test_dataRF_Album$Engagements) * .80)
numberOfTrainingSamples_XGPhoto <- round(length(test_dataRF_Photo$Engagements) * .80)

train_data_XGVideo <- XG_Video_matrix[1:numberOfTrainingSamples_XGVideo,]
train_labels_XGVideo <- XG_Video_labels[1:numberOfTrainingSamples_XGVideo,]
test_data_XGVideo <- XG_Video_matrix[-(1:numberOfTrainingSamples_XGVideo),]
test_labels_XGVideo <- XG_Video_labels[-(1:numberOfTrainingSamples_XGVideo),]

train_data_XGAlbum <- XG_Album_matrix[1:numberOfTrainingSamples_XGAlbum,]
train_labels_XGAlbum <- XG_Album_labels[1:numberOfTrainingSamples_XGAlbum,]
test_data_XGAlbum <- XG_Album_matrix[-(1:numberOfTrainingSamples_XGAlbum),]
test_labels_XGAlbum <- XG_Album_labels[-(1:numberOfTrainingSamples_XGAlbum),]

train_data_XGPhoto <- XG_Photo_matrix[1:numberOfTrainingSamples_XGPhoto,]
train_labels_XGPhoto <- XG_Photo_labels[1:numberOfTrainingSamples_XGPhoto,]
test_data_XGPhoto <- XG_Photo_matrix[-(1:numberOfTrainingSamples_XGPhoto),]
test_labels_XGPhoto <- XG_Photo_labels[-(1:numberOfTrainingSamples_XGPhoto),]

# DMatrix formation
dtrain_XGVideo <- xgb.DMatrix(data = train_data_XGVideo, label= train_labels_XGVideo)
dtest_XGVideo <- xgb.DMatrix(data = test_data_XGVideo, label= test_labels_XGVideo)

dtrain_XGAlbum <- xgb.DMatrix(data = train_data_XGAlbum, label= train_labels_XGAlbum)
dtest_XGAlbum <- xgb.DMatrix(data = test_data_XGAlbum, label= test_labels_XGAlbum)

dtrain_XGPhoto <- xgb.DMatrix(data = train_data_XGPhoto, label= train_labels_XGPhoto)
dtest_XGPhoto <- xgb.DMatrix(data = test_data_XGPhoto, label= test_labels_XGPhoto)
```


```{r results = 'hide'}
### Create XGBoosting Model
boost_model_video <- xgboost(data = dtrain_XGVideo, nround = 300, max.depth = 2, early_stopping_rounds = 2)
boost_model_album <- xgboost(data = dtrain_XGAlbum, nround = 300, max.depth = 2, early_stopping_rounds = 2)
boost_model_photo <- xgboost(data = dtrain_XGPhoto, nround = 300, max.depth = 2, early_stopping_rounds = 2)
```

```{r}
### Calculate MAPE (Test Set Predictions)

prediction_xgboost_video = Calc_Predicted(boost_model_video, dtest_XGVideo)
prediction_xgboost_album = Calc_Predicted(boost_model_album, dtest_XGAlbum)
prediction_xgboost_photo = Calc_Predicted(boost_model_photo, dtest_XGPhoto)
mape_XGVideo = Calc_Mape(test_labels_XGVideo,dtest_XGVideo, boost_model_video)
mape_XGAlbum = Calc_Mape(test_labels_XGAlbum,dtest_XGAlbum, boost_model_album)
mape_XGPhoto = Calc_Mape(test_labels_XGPhoto,dtest_XGPhoto, boost_model_photo)

#dataset
df_boost_Video = cbind(test_data_XGVideo, test_labels_XGVideo, prediction_xgboost_video)
df_boost_Album = cbind(test_data_XGAlbum, test_labels_XGAlbum, prediction_xgboost_album)
df_boost_Photo = cbind(test_data_XGPhoto, test_labels_XGPhoto, prediction_xgboost_photo)

colnames(df_boost_Video)[colnames(df_boost_Video) == 'prediction_xgboost_video'] <- 'predictions_XG'
colnames(df_boost_Album)[colnames(df_boost_Album) == 'prediction_xgboost_album'] <- 'predictions_XG'
colnames(df_boost_Photo)[colnames(df_boost_Photo) == 'prediction_xgboost_photo'] <- 'predictions_XG'

colnames(df_boost_Video)[colnames(df_boost_Video) == 'test_labels_XGVideo'] <- 'Engagements'
colnames(df_boost_Album)[colnames(df_boost_Album) == 'test_labels_XGAlbum'] <- 'Engagements'
colnames(df_boost_Photo)[colnames(df_boost_Photo) == 'test_labels_XGPhoto'] <- 'Engagements'

df_boost_trained_final = rbind(df_boost_Video, df_boost_Album, df_boost_Photo)

```


```{r}
df_boost_train_final <- as.data.frame(df_boost_trained_final)
df_boost_train_final$APE = abs((df_boost_train_final$Engagements - df_boost_train_final$predictions_XG)/df_boost_train_final$Engagements) * 100
mape = mean(df_boost_train_final$APE)
print(mape)
test_data_net$percent_error[test_data_net$percent_error >25]
df_boost_train_final$APE[df_boost_train_final$APE > 25]
hist(df_boost_train_final$APE[df_boost_train_final$APE > 20], breaks = 50)
hist(test_data_net$percent_error[test_data_net$percent_error >25], breaks=50, col = 'red')
```

```{r}

xgb.cv(data = train_data_XGVideo, label = train_labels_XGVideo, nfold = 5,
                 nrounds = 100)
xgb.cv(data = train_data_XGAlbum, label = train_labels_XGAlbum, nfold = 5,
                 nrounds = 100)
xgb.cv(data = train_data_XGPhoto, label = train_labels_XGPhoto, nfold = 5,
                 nrounds = 100)
```

```{r}
#Linear Models
  
traindata_video_lm <- test_dataRF_Video[1:numberOfTrainingSamples_XGVideo,]
testdata_video_lm <- test_dataRF_Video[-(1:numberOfTrainingSamples_XGVideo),]

traindata_album_lm <- test_dataRF_Album[1:numberOfTrainingSamples_XGAlbum,]
testdata_album_lm <- test_dataRF_Album[-(1:numberOfTrainingSamples_XGAlbum),]

traindata_photo_lm <- test_dataRF_Photo[1:numberOfTrainingSamples_XGPhoto,]
testdata_photo_lm <- test_dataRF_Photo[-(1:numberOfTrainingSamples_XGPhoto),]

lmV = lm(Engagements ~ Followers+wkdy_num+num_hash+Followers_Mentioned+all_nba+is_playoffs+day_time+league_type+month_int+predicted, data=traindata_video_lm)
lmA = lm(Engagements ~ Followers+wkdy_num+num_hash+Followers_Mentioned+all_nba+is_playoffs+day_time+league_type+month_int+predicted, data=traindata_album_lm)
lmP = lm(Engagements ~ Followers+wkdy_num+num_hash+Followers_Mentioned+all_nba+is_playoffs+day_time+league_type+month_int+predicted, data=traindata_photo_lm)
mape_lm_video = Calc_Mape(testdata_video_lm$Engagements, testdata_video_lm ,lmV)
mape_lm_album = Calc_Mape(testdata_album_lm$Engagements, testdata_album_lm ,lmA)
mape_lm_photo = Calc_Mape(testdata_photo_lm$Engagements, testdata_photo_lm ,lmP)

```

```{r}
holdout <- read.csv("~/Desktop/NBA Analytics/Business Analytics/holdout.csv")
holdout$Engagements = 
for (i in holdout)
  {
    if (holdout$type[i] == 1)
      {
          holdout$Engagements[i] = Calc_Predicted(xgboosted_Video, holdout)
    }
    if (holdout$type[i] == 2)
      {
          holdout$Engagements[i] = Calc_Predicted(xgboosted_Photo, holdout)
    }
    if (holdout$type[i] == 3)
      {
          holdout$Engagements[i] = Calc_Predicted(xgboosted_Album, holdout)
      }
  }


```

\textbf{Extra Variable Creation Script}

```{r}
## Create variables for number of people and number of hashtags
## mentioned, turn weekdays and post type into numbers, and clean is_season variable.

df <- read.csv("~/Desktop/NBA_Analytics/nba-business-hackathon/data/training_set_extended_5.csv")

nba <- df %>% 
  mutate(num_ats = str_count(Description, "@"),
         num_hash = str_count(Description, "#"))

nba$Type_num <- NA
for(i in 1:length(nba[,1])){
  if(nba$Type[i] == "Video")(nba$Type_num[i] = 1)
  if(nba$Type[i] == "Photo")(nba$Type_num[i] = 2)
  if(nba$Type[i] == "Album")(nba$Type_num[i] = 3)
}
nba$wkdy_num <- NA
for(i in 1:length(nba[,1])){
  if(nba$weekday[i] == "Sunday")(nba$wkdy_num[i] = 1)
  if(nba$weekday[i] == "Monday")(nba$wkdy_num[i] = 2)
  if(nba$weekday[i] == "Tuesday")(nba$wkdy_num[i] = 3)
  if(nba$weekday[i] == "Wednesday")(nba$wkdy_num[i] = 4)
  if(nba$weekday[i] == "Thursday")(nba$wkdy_num[i] = 5)
  if(nba$weekday[i] == "Friday")(nba$wkdy_num[i] = 6)
  if(nba$weekday[i] == "Saturday")(nba$wkdy_num[i] = 7)
}
nba$day_time_num <- NA
for(i in 1:length(nba[,1])){
  if(nba$day_time[i] == "deadzone")(nba$day_time_num[i] = 1)
  if(nba$day_time[i] == "morning")(nba$day_time_num[i] = 2)
  if(nba$day_time[i] == "lunch")(nba$day_time_num[i] = 3)
  if(nba$day_time[i] == "afternoon")(nba$day_time_num[i] = 4)
  if(nba$day_time[i] == "evening")(nba$day_time_num[i] = 5)
  if(nba$day_time[i] == "night")(nba$day_time_num[i] = 6)
  if(nba$day_time[i] == "postgame")(nba$day_time_num[i] = 7)
}

# Delete irrelevant indexing columns.
nba <- nba[,-c(1,2)]
write.csv(nba, file = "training_set_final.csv")

```

```{r}
nba_graphs <- nba
nba_graphs$is_playoffs = as.factor(nba$is_playoffs)
nba_graphs$all_nba = as.factor(nba$all_nba)
nba_graphs$league_type = as.factor(nba$league_type)
nba_graphs$is_season = as.factor(nba$is_season)
nba_graphs$same_day_post = as.factor(nba$same_day_post)
nba_graphs$num_ats = as.factor(nba$num_ats)
nba_graphs$num_hash = as.factor(nba$num_hash)

g <- ggplot(nba_graphs, aes(x = Type, y = Engagements, fill = month))
g + geom_boxplot(position = "dodge", outlier.shape=NA) + labs(title="Engagements by Month", x= "Month", y="Engagements") + theme_minimal()

#scale_x_discrete(limits = c("October", "November", "December","January", "February","March", "April","May","June","July","August","September"))

g <- ggplot(nba_graphs, aes(x = Type, y = Engagements, fill = weekday))
g + geom_boxplot(position = "dodge",outlier.shape=NA) + labs(title="Engagements by Day", x= "Weekday", y="Engagements") + theme_minimal()

#scale_x_discrete(limits = c("Monday", "Tuesday", "Wednesday", "Thursday","Friday", "Saturday","Sunday"))

g <- ggplot(nba_graphs, aes(x = Type, y = Engagements, fill = day_time))
g + geom_boxplot(position = "dodge", outlier.shape=NA) + labs(title="Engagements by Time of Day", x= "day_time", y="Engagements") + theme_minimal()

#+ scale_x_discrete(limits = c("deadzone", "morning", "lunch", "afternoon","evening", "night","postgame"))


g <- ggplot(nba_graphs, aes(x = Type, y = Engagements, fill = is_season))
g + geom_boxplot(position = "dodge", outlier.shape=NA) + labs(title="Effect of Being In Season on Engagements", x= "Season or Off-Season", y="Engagements") + theme_minimal()

g <- ggplot(nba_graphs, aes(x = Type, y = Engagements, fill = is_playoffs))
g + geom_boxplot(position = "dodge", outlier.shape=NA) + labs(title="Effect of Playoff Season on Engagements", x= "During Playoffs", y="Engagements") + theme_minimal()

g <- ggplot(nba_graphs, aes(x = Type, y = Engagements, fill = all_nba))
g + geom_boxplot(position = "dodge", outlier.shape=NA) + labs(title="Effect of Star Players on Engagements", x= "Type of Star Players", y="Engagements") + theme_minimal()

g <- ggplot(nba_graphs, aes(x = Type, y = Engagements, fill = league_type))
g + geom_boxplot(position = "dodge", outlier.shape=NA) + labs(title="Effect of NBA vs GLeague vs WNBA on Engagements", x= "Type of League", y="Engagements") + theme_minimal()

g <- ggplot(nba_graphs, aes(x = Type, y = Engagements, fill = same_day_post))
g + geom_boxplot(position = "dodge", outlier.shape=NA) + labs(title="Effect of Posting in the Same Time Period", x= "Same Time Period", y="Engagements") + theme_minimal()

```

```{r}
```{r}
#varsVid = colnames(train_dataRF_Video[c(2,8,10,11,12,14,15,16,17,18,19,20)])
#varsPhoto = colnames(train_dataRF_Photo[c(2,8,10,11,12,14,15,16,17,18,19,20)])
#varsAlbum = colnames(train_dataRF_Album[c(2,8,10,11,12,14,15,16,17,18,19,20)])
```

```